In [1]:
# We do it as a part of preprocessing the data

In [5]:
import numpy as np
from sklearn import preprocessing

In [6]:
X = np.array([[1.,-1.,2.],
              [2.,0.,0.],
              [0.,1.,-1.]])

In [8]:
x_scaled = preprocessing.scale(X) #Scale basically tries to make mean to be 0 and variance to be 1

In [12]:
x_scaled.mean(axis=0) #Mean around x

array([0., 0., 0.])

In [14]:
x_scaled.std(axis=0) #Standard Deviation = 1

array([1., 1., 1.])

In [18]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)
scaler.transform(X) # Same as scale but here we have store the parameters for future scaling of our testing data

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [19]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])